(dp1
S'bedDN'
p2
S'D'
sS'legsDN'
p3
S'E'
sS'sit'
p4
cnumpy.core.multiarray
_reconstruct
p5
(cnumpy
ndarray
p6
(I0
tS'b'
tRp7
(I1
(I3
tcnumpy
dtype
p8
(S'f8'
I0
I1
tRp9
(I3
S'<'
NNNI-1
I-1
I0
tbI00
S'Z\x95\x8c3\xd2\x91J@\x85\xe9]r\x8fF\x1f@\x00\x00\x00\x00\x00\x00\x00\x00'
tbsS'headDN'
p10
S'F'
sS'legsUP'
p11
S'B'
sS'headUP'
p12
S'A'
sS'bedUP'
p13
S'C'
s.