(dp1
S'test1'
p2
cnumpy.core.multiarray
_reconstruct
p3
(cnumpy
ndarray
p4
(I0
tS'b'
tRp5
(I1
(I3
tcnumpy
dtype
p6
(S'f8'
I0
I1
tRp7
(I3
S'<'
NNNI-1
I-1
I0
tbI00
S'4r\x08\xe0\xf0\xa5I@\xb4\xb3\xb5iP\xd28@P\xfe\x06\x96\x08h+@'
tbsS'bedDN'
p8
S'B'
sS'legsDN'
p9
S'C'
sS'headDN'
p10
S'A'
sS'legsUP'
p11
S'E'
sS'headUP'
p12
S'F'
sS'bedUP'
p13
S'D'
s.