(dp1
S'test1'
p2
cnumpy.core.multiarray
_reconstruct
p3
(cnumpy
ndarray
p4
(I0
tS'b'
tRp5
(I1
(I3
tcnumpy
dtype
p6
(S'f8'
I0
I1
tRp7
(I3
S'<'
NNNI-1
I-1
I0
tbI00
S'\\ \xea\x9c\xda\x88N@owf5"\x1a&@\xd0\x08X\xf8519@'
tbsS'supine'
p8
g3
(g4
(I0
tS'b'
tRp9
(I1
(I3
tg6
(S'f8'
I0
I1
tRp10
(I3
S'<'
NNNI-1
I-1
I0
tbI00
S':\x13\xec\x93\x00\x8a\x1a@K\xff\xb8\xfeyv,@\x00\x00\x00\x00\x00\x00\x00\x00'
tbsS'feeding_task'
p11
g3
(g4
(I0
tS'b'
tRp12
(I1
(I3
tg6
(S'f8'
I0
I1
tRp13
(I3
S'<'
NNNI-1
I-1
I0
tbI00
S'\x00\x00\x00\x00\x00\x00T@\xa5EB\xf53V)@\xd0t\x8c\xe5\xbd\xa2 @'
tbsS'demo'
p14
g3
(g4
(I0
tS'b'
tRp15
(I1
(I3
tg6
(S'f8'
I0
I1
tRp16
(I3
S'<'
NNNI-1
I-1
I0
tbI00
S'\xaalf\xa9s\xd3=@\xa1HjC\xc6\xcc*@\xbcC\x99{\xd0~5@'
tbsS'test_new_sensor'
p17
g3
(g4
(I0
tS'b'
tRp18
(I1
(I3
tg6
(S'f8'
I0
I1
tRp19
(I3
S'<'
NNNI-1
I-1
I0
tbI00
S'\x1e\x8b\x9cN\xcd\x8dE@\x1d\xa4H\xff\x06\x98\x1e@J!\x95\xa8\xbcFM@'
tbsS'down'
p20
g3
(g4
(I0
tS'b'
tRp21
(I1
(I3
tg6
(S'f8'
I0
I1
tRp22
(I3
S'<'
NNNI-1
I-1
I0
tbI00
S'F\xc7\xdb\x1f\x1c\xc1\x1c@\xbf<3\x9a-\xe1)@\x00\x00\x00\x00\x00\x00\x00\x00'
tbsS'test_head_legs'
p23
g3
(g4
(I0
tS'b'
tRp24
(I1
(I3
tg6
(S'f8'
I0
I1
tRp25
(I3
S'<'
NNNI-1
I-1
I0
tbI00
S'\xe4W\x1f\x1fi\xc6;@\x8f\x83\x89\x8d\xf8\x1a&@j!\xd6\\\xbc\xbaB@'
tbsS'test_pose_527'
p26
g3
(g4
(I0
tS'b'
tRp27
(I1
(I3
tg6
(S'f8'
I0
I1
tRp28
(I3
S'<'
NNNI-1
I-1
I0
tbI00
S'?`\xff\x94%U?@)\xbb\xe3\xe6O).@L\xea\x1aj\xde\xb8C@'
tbsS'pose1'
p29
g3
(g4
(I0
tS'b'
tRp30
(I1
(I3
tg6
(S'f8'
I0
I1
tRp31
(I3
S'<'
NNNI-1
I-1
I0
tbI00
S'T\x95e\x1c\x0f\xc8=@\x7f\\\x18\x132W,@\xb0\x0c\xf8\xb2Sf2@'
tbsS'new pose'
p32
g3
(g4
(I0
tS'b'
tRp33
(I1
(I3
tg6
(S'f8'
I0
I1
tRp34
(I3
S'<'
NNNI-1
I-1
I0
tbI00
S'n6\xa4\xbb\xd6\x83K@\x10\xd4\x11)\xec)-@\xdc\x11\xf8B \x916@'
tbs.